apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: default
data:
  config.yaml: |
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces: ["**"]
    server:
      port: 20001
      web_root: /kiali
