# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: prometheus
#   namespace: default
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: prometheus
#   labels:
#     app.kubernetes.io/component: server
#     app.kubernetes.io/name: prometheus
# rules:
#   - apiGroups: [""]
#     resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["extensions"]
#     resources: ["ingresses"]
#     verbs: ["get", "list", "watch"]
#   - nonResourceURLs: ["/metrics"]
#     verbs: ["get"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: prometheus
#   labels:
#     app.kubernetes.io/component: server
#     app.kubernetes.io/name: prometheus
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: prometheus
# subjects:
#   - kind: ServiceAccount
#     name: prometheus
#     namespace: default
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   namespace: default
# spec:
#   ports:
#     - port: 9090
#       targetPort: 9090
#   selector:
#     app: prometheus
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: prometheus
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: prometheus
#   template:
#     metadata:
#       labels:
#         app: prometheus
#     spec:
#       serviceAccountName: prometheus
#       containers:
#         - name: prometheus
#           image: prom/prometheus
#           ports:
#             - containerPort: 9090
